# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set environment variables for Python to avoid buffering issues
ENV PYTHONUNBUFFERED=1


WORKDIR / Dockerfile_1


COPY . /Dockerfile_1

# Install required packages from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 80 to allow external traffic to the container
EXPOSE 80

# Run a custom entrypoint script to show runtime information
ENTRYPOINT ["sh", "-c", "echo 'Starting Order Management System'; echo 'Running on $(hostname) at $(date)'; python cs330_04_1.py"]
